services:
  spark:
    build: .
    image: tradecorp-pyspark:latest
    container_name: tradecorp_spark
    env_file: 
      - .env
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./tests:/home/jovyan/tests
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      #PYTHONPATH: /home/jovyan/src
      PYTHONPATH: "/usr/local/spark/python/lib/py4j-0.10.9.9-src.zip:/usr/local/spark/python:/home/jovyan/src"
      PYSPARK_SUBMIT_ARGS: "--packages org.postgresql:postgresql:42.7.0 pyspark-shell"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: tradecorp_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - tradecorp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: tradecorp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8086:80"
    volumes:
      - tradecorp_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  tradecorp_pgdata:
  tradecorp_pgadmin_data: